// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: butterfish.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//	*ClientPush_ClientOpen
	//	*ClientPush_ClientInput
	//	*ClientPush_ClientOutput
	Msg isClientPush_Msg `protobuf_oneof:"msg"`
}

func (x *ClientPush) Reset() {
	*x = ClientPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPush) ProtoMessage() {}

func (x *ClientPush) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPush.ProtoReflect.Descriptor instead.
func (*ClientPush) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{0}
}

func (m *ClientPush) GetMsg() isClientPush_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ClientPush) GetClientOpen() *ClientOpen {
	if x, ok := x.GetMsg().(*ClientPush_ClientOpen); ok {
		return x.ClientOpen
	}
	return nil
}

func (x *ClientPush) GetClientInput() *ClientInput {
	if x, ok := x.GetMsg().(*ClientPush_ClientInput); ok {
		return x.ClientInput
	}
	return nil
}

func (x *ClientPush) GetClientOutput() *ClientOutput {
	if x, ok := x.GetMsg().(*ClientPush_ClientOutput); ok {
		return x.ClientOutput
	}
	return nil
}

type isClientPush_Msg interface {
	isClientPush_Msg()
}

type ClientPush_ClientOpen struct {
	ClientOpen *ClientOpen `protobuf:"bytes,1,opt,name=client_open,json=clientOpen,proto3,oneof"`
}

type ClientPush_ClientInput struct {
	ClientInput *ClientInput `protobuf:"bytes,2,opt,name=client_input,json=clientInput,proto3,oneof"`
}

type ClientPush_ClientOutput struct {
	ClientOutput *ClientOutput `protobuf:"bytes,3,opt,name=client_output,json=clientOutput,proto3,oneof"`
}

func (*ClientPush_ClientOpen) isClientPush_Msg() {}

func (*ClientPush_ClientInput) isClientPush_Msg() {}

func (*ClientPush_ClientOutput) isClientPush_Msg() {}

type ClientOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClientOutput) Reset() {
	*x = ClientOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOutput) ProtoMessage() {}

func (x *ClientOutput) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOutput.ProtoReflect.Descriptor instead.
func (*ClientOutput) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{1}
}

func (x *ClientOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClientOpen struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WrappedCommand string `protobuf:"bytes,1,opt,name=wrappedCommand,proto3" json:"wrappedCommand,omitempty"`
}

func (x *ClientOpen) Reset() {
	*x = ClientOpen{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOpen) ProtoMessage() {}

func (x *ClientOpen) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOpen.ProtoReflect.Descriptor instead.
func (*ClientOpen) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{2}
}

func (x *ClientOpen) GetWrappedCommand() string {
	if x != nil {
		return x.WrappedCommand
	}
	return ""
}

type ClientInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClientInput) Reset() {
	*x = ClientInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInput) ProtoMessage() {}

func (x *ClientInput) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInput.ProtoReflect.Descriptor instead.
func (*ClientInput) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{3}
}

func (x *ClientInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ServerPush) Reset() {
	*x = ServerPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPush) ProtoMessage() {}

func (x *ServerPush) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPush.ProtoReflect.Descriptor instead.
func (*ServerPush) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{4}
}

func (x *ServerPush) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Represents the constituent files of a directory, this should map a relative
// path from the directory to a file within it (but not within a child dir).
type DirectoryIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string should be a relative path, e.g. "./foo.txt"
	Files map[string]*FileEmbeddings `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DirectoryIndex) Reset() {
	*x = DirectoryIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectoryIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryIndex) ProtoMessage() {}

func (x *DirectoryIndex) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryIndex.ProtoReflect.Descriptor instead.
func (*DirectoryIndex) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{5}
}

func (x *DirectoryIndex) GetFiles() map[string]*FileEmbeddings {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileEmbeddings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // filename, relative path to the DirectoryIndex, e.g. ./foo
	// When the embedding was created, if an earlier timestamp than the file
	// edit time then the file should be re-embedded.
	UpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Embeddings []*AnnotatedEmbedding  `protobuf:"bytes,3,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
}

func (x *FileEmbeddings) Reset() {
	*x = FileEmbeddings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileEmbeddings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEmbeddings) ProtoMessage() {}

func (x *FileEmbeddings) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEmbeddings.ProtoReflect.Descriptor instead.
func (*FileEmbeddings) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{6}
}

func (x *FileEmbeddings) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEmbeddings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *FileEmbeddings) GetEmbeddings() []*AnnotatedEmbedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type AnnotatedEmbedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start  uint64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"` // start index in bytes to the file chunk
	End    uint64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`     // end index in bytes to the file chunk
	Vector []float64 `protobuf:"fixed64,4,rep,packed,name=vector,proto3" json:"vector,omitempty"`
}

func (x *AnnotatedEmbedding) Reset() {
	*x = AnnotatedEmbedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_butterfish_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnnotatedEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnotatedEmbedding) ProtoMessage() {}

func (x *AnnotatedEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_butterfish_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnotatedEmbedding.ProtoReflect.Descriptor instead.
func (*AnnotatedEmbedding) Descriptor() ([]byte, []int) {
	return file_butterfish_proto_rawDescGZIP(), []int{7}
}

func (x *AnnotatedEmbedding) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *AnnotatedEmbedding) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *AnnotatedEmbedding) GetVector() []float64 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_butterfish_proto protoreflect.FileDescriptor

var file_butterfish_proto_rawDesc = []byte{
	0x0a, 0x10, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x75,
	0x73, 0x68, 0x12, 0x2e, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x70, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4f, 0x70, 0x65, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x12, 0x31, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x22, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x34, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4f, 0x70, 0x65, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x64, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x21, 0x0a, 0x0b,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x20, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x30, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x49, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x94, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x65, 0x64, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x0a, 0x65, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x54, 0x0a, 0x12, 0x41, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x01, 0x52, 0x06, 0x76, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x42,
	0x0a, 0x0a, 0x42, 0x75, 0x74, 0x74, 0x65, 0x72, 0x66, 0x69, 0x73, 0x68, 0x12, 0x34, 0x0a, 0x12,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x46, 0x6f, 0x72, 0x57, 0x72, 0x61, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x12, 0x0b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x73, 0x68, 0x1a,
	0x0b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x65, 0x67, 0x6c, 0x6f, 0x6e, 0x2f, 0x62, 0x75, 0x74, 0x74, 0x65, 0x72, 0x66, 0x69,
	0x73, 0x68, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_butterfish_proto_rawDescOnce sync.Once
	file_butterfish_proto_rawDescData = file_butterfish_proto_rawDesc
)

func file_butterfish_proto_rawDescGZIP() []byte {
	file_butterfish_proto_rawDescOnce.Do(func() {
		file_butterfish_proto_rawDescData = protoimpl.X.CompressGZIP(file_butterfish_proto_rawDescData)
	})
	return file_butterfish_proto_rawDescData
}

var file_butterfish_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_butterfish_proto_goTypes = []interface{}{
	(*ClientPush)(nil),            // 0: ClientPush
	(*ClientOutput)(nil),          // 1: ClientOutput
	(*ClientOpen)(nil),            // 2: ClientOpen
	(*ClientInput)(nil),           // 3: ClientInput
	(*ServerPush)(nil),            // 4: ServerPush
	(*DirectoryIndex)(nil),        // 5: DirectoryIndex
	(*FileEmbeddings)(nil),        // 6: FileEmbeddings
	(*AnnotatedEmbedding)(nil),    // 7: AnnotatedEmbedding
	nil,                           // 8: DirectoryIndex.FilesEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_butterfish_proto_depIdxs = []int32{
	2, // 0: ClientPush.client_open:type_name -> ClientOpen
	3, // 1: ClientPush.client_input:type_name -> ClientInput
	1, // 2: ClientPush.client_output:type_name -> ClientOutput
	8, // 3: DirectoryIndex.files:type_name -> DirectoryIndex.FilesEntry
	9, // 4: FileEmbeddings.updated_at:type_name -> google.protobuf.Timestamp
	7, // 5: FileEmbeddings.embeddings:type_name -> AnnotatedEmbedding
	6, // 6: DirectoryIndex.FilesEntry.value:type_name -> FileEmbeddings
	0, // 7: Butterfish.StreamsForWrapping:input_type -> ClientPush
	4, // 8: Butterfish.StreamsForWrapping:output_type -> ServerPush
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_butterfish_proto_init() }
func file_butterfish_proto_init() {
	if File_butterfish_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_butterfish_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientOpen); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DirectoryIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileEmbeddings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_butterfish_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnnotatedEmbedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_butterfish_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientPush_ClientOpen)(nil),
		(*ClientPush_ClientInput)(nil),
		(*ClientPush_ClientOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_butterfish_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_butterfish_proto_goTypes,
		DependencyIndexes: file_butterfish_proto_depIdxs,
		MessageInfos:      file_butterfish_proto_msgTypes,
	}.Build()
	File_butterfish_proto = out.File
	file_butterfish_proto_rawDesc = nil
	file_butterfish_proto_goTypes = nil
	file_butterfish_proto_depIdxs = nil
}
