Output gif/goal.gif

Set CursorBlink false
Require butterfish

Set FontSize 26
Set Padding 14
Set Theme "Monokai Pro"
Set PlaybackSpeed 0.8
Set Framerate 20

Hide

Type "cd ~/butterfish" Enter
Enter
Type "clear"
Enter

Sleep 2s Show


Type "butterfish shell -m gpt-4"
Sleep 1s
Enter
Sleep 2s

Type "!!Show the largest files in this dir, recursively, not directories themselves"
Sleep 1s
Enter
Sleep 45s

