Output gif/index.gif

Set CursorBlink false
Require butterfish

Set FontSize 20
Set Padding 14
Set Theme "Monokai Pro"
Set PlaybackSpeed 1.0
Set Framerate 20

Hide

Type "cd ~/butterfish"
Enter
Type "butterfish clearindex"
Enter
Type "clear"
Enter

Sleep 2s Show

Type "butterfish index README.md"
Sleep 3s
Enter
Sleep 5s

Type "butterfish indexsearch -r 2 'summarize command'"
Sleep 3s
Enter
Sleep 30s
