Output gif/prompt.gif

Require butterfish

Set FontSize 18
Set Width 1000
Set Height 500
Set Framerate 30
Set PlaybackSpeed 1
Set Padding 10

Hide Sleep 2s Show

Type "butterfish prompt 'I need to parse a directory full of log files and find lines with the string ERROR, then sort based on a timestamp in the line. How can I do this from the command line, give me a specific suggestion and include examples:'"
Sleep 1s
Enter

Sleep 30s
