Output gif/shell2.gif

Set CursorBlink false
Require butterfish

Set FontSize 24
Set Padding 14
Set Theme "Monokai Pro"
Set PlaybackSpeed 1.0
Set Framerate 20

Hide

Type "cd ~/butterfish" Enter
Type "clear"
Enter

Sleep 2s Show

Type "butterfish shell -m gpt-4"
Sleep 1s
Enter
Sleep 2s

Type "ls"
Sleep 1s
Enter
Sleep 3s

Type "How do I find go files in this dir?"
Sleep 1s
Enter
Sleep 8s

Tab
Sleep 1s
Enter
Sleep 5s

Type "How do I sort them by size?"
Sleep 1s
Enter
Sleep 8s

Tab
Sleep 1s
Enter
Sleep 20s

