Output gif/shell3.gif

Set CursorBlink false
Require butterfish

Set FontSize 26
Set Padding 14
Set Theme "Monokai Pro"
Set PlaybackSpeed 0.8
Set Framerate 20

Hide

Type "mkdir ~/project" Enter
Type "cd ~/project" Enter
Type "rm *" Enter
Type "echo foo aoeuao euaoeuaoeut > foo.js" Enter
Type "echo foo aoeuaoeuaoeu > bar.js" Enter
Enter
Type "clear"
Enter

Sleep 2s Show


Type "butterfish shell -m gpt-4"
Sleep 1s
Enter
Sleep 2s

Type "ls"
Sleep 1s
Enter
Sleep 4s

Type "Are these files executable?
Sleep 1s
Enter
Sleep 15s

Type "How do I make foo.js executable?"
Sleep 1s
Enter
Sleep 12s

Tab
Sleep 1s
Enter
Sleep 4s

Type "ls"
Sleep 1s
Enter
Sleep 30s
